---
########################################################################################################################################################
## Preinstalled Packages
#########################################################################################################################################################
- name: Ensure a list of pachages installed
  yum:
    name: "/tmp/rpm-packages/{{ packages }}"
    state: installed
  vars:
# per packages
    packages:
    - python36
    - python36-asn1crypto
    - python36-pycryptodomex
    - python36-pysocks
    - python36-slacker                             
    - python36-setuptools                                    
    - python36-urllib3                              
#    - python36-jsmva        #                           
    - python36-nose
#    - python3-pip           #
# nagios packages
    - nagios-plugins-all
    - nagios-plugins-uptime        

