---
########################################################################################################################################################
## Preinstalled Packages
#########################################################################################################################################################
- name: Ensure a list of pachages installed
  yum:
    name: "{{ packages }}"
    state: installed
  vars:
# packages that are included in the channels in AWS
    packages:
    - createrepo
    - logrotate
    - telnet
    - nmap-ncat
    - screen
    - tmux
    - sysstat
    - python-pip
    - pexpect
    - perl
    - perl(JSON)
    - perl(Digest::MD5)
    - perl(Config::IniFiles)
    - perl(Sys::Statistics::Linux)
# amzn2-core

